// Generated by gencpp from file motor_driver/Pwm.msg
// DO NOT EDIT!


#ifndef MOTOR_DRIVER_MESSAGE_PWM_H
#define MOTOR_DRIVER_MESSAGE_PWM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_driver
{
template <class ContainerAllocator>
struct Pwm_
{
  typedef Pwm_<ContainerAllocator> Type;

  Pwm_()
    : pwmA(0)
    , pwmB(0)  {
    }
  Pwm_(const ContainerAllocator& _alloc)
    : pwmA(0)
    , pwmB(0)  {
  (void)_alloc;
    }



   typedef int32_t _pwmA_type;
  _pwmA_type pwmA;

   typedef int32_t _pwmB_type;
  _pwmB_type pwmB;





  typedef boost::shared_ptr< ::motor_driver::Pwm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_driver::Pwm_<ContainerAllocator> const> ConstPtr;

}; // struct Pwm_

typedef ::motor_driver::Pwm_<std::allocator<void> > Pwm;

typedef boost::shared_ptr< ::motor_driver::Pwm > PwmPtr;
typedef boost::shared_ptr< ::motor_driver::Pwm const> PwmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_driver::Pwm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_driver::Pwm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_driver::Pwm_<ContainerAllocator1> & lhs, const ::motor_driver::Pwm_<ContainerAllocator2> & rhs)
{
  return lhs.pwmA == rhs.pwmA &&
    lhs.pwmB == rhs.pwmB;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_driver::Pwm_<ContainerAllocator1> & lhs, const ::motor_driver::Pwm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motor_driver::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_driver::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_driver::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_driver::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_driver::Pwm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_driver::Pwm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_driver::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c46853c782ce10c35ceede0e24a5cb8";
  }

  static const char* value(const ::motor_driver::Pwm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c46853c782ce10cULL;
  static const uint64_t static_value2 = 0x35ceede0e24a5cb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_driver::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_driver/Pwm";
  }

  static const char* value(const ::motor_driver::Pwm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_driver::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pwmA\n"
"int32 pwmB\n"
;
  }

  static const char* value(const ::motor_driver::Pwm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_driver::Pwm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwmA);
      stream.next(m.pwmB);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pwm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_driver::Pwm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_driver::Pwm_<ContainerAllocator>& v)
  {
    s << indent << "pwmA: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pwmA);
    s << indent << "pwmB: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pwmB);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_DRIVER_MESSAGE_PWM_H
